server:
  port: 8081

spring:
  application:
    name: product-service

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        acl-token: e95b599e-166e-7d80-08ad-aee76e7ddf19
